### PR TITLE
feat: Add `github_actions_enterprise_permissions`

### PR DESCRIPTION
**Pull request by ErikElkins**
Resolves part of #1199 

This adds a new resource `github_actions_enterprise_permissions` to control GitHub Actions policy on an enterprise.

```tf
data "github_enterprise" "example-enterprise" {
  slug = "my-enterprise"
}

data "github_organization" "example-org" {
  name = "my-org"
}

resource "github_actions_enterprise_permissions" "test" {
  enterprise_id = data.github_enterprise.example-enterprise.slug
  allowed_actions = "selected"
  enabled_organizations = "selected"
  allowed_actions_config {
    github_owned_allowed = true 
    patterns_allowed     = ["actions/cache@*", "actions/checkout@*"]
    verified_allowed     = true
  }
  enabled_organizations_config {
    organization_ids = [data.github_organization.example-org.id]
  }
}
```

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Comment by kfcampbell** [comment]
When running the new integration tests, I get the following error: 

```
    resource_github_actions_enterprise_permissions_test.go:261: Step 1/1 error: Error running pre-apply refresh: exit status 1
        
        Error: Could not resolve to a Business with the URL slug of ''.
        
          with data.github_enterprise.enterprise,
          on terraform_plugin_test.tf line 3, in data "github_enterprise" "enterprise":
           3: 			data "github_enterprise" "enterprise" {
        
```

Can you reproduce this? Am I missing some kind of setup?

**Comment by ErikElkins** [comment]
I missed the check on `ENTERPRISE_SLUG` and `ENTERPRISE_ACCOUNT` that the other enterprise dependent integration tests do here: https://github.com/integrations/terraform-provider-github/blob/main/github/resource_github_enterprise_organization_test.go#L91

Updated the PR.

**Comment by kfcampbell** [comment]
@laughedelic good catch. I have a slight preference for `github_enterprise_actions...` since these are settings that only exist in enterprise, though I'd be happy to hear arguments either way.

**Comment by ErikElkins** [comment]
I named this after `[github_actions_organization_permissions](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/actions_organization_permissions)`. But if we think there will be more enterprise resources, `github_enterprise...` would be better.

**Review by kfcampbell — APPROVED** [review]
I don't have easy access to an enterprise for manual validation so please let me know if something isn't behaving right!

**Pull request merged**
