### PR TITLE
Support for allow_forking on a repository/update to go-github v42

### PR DESCRIPTION
**Pull request by diogopms**
Support enabling/disabling allow_forking on a repository as per #353
[More info on the Github Public API](https://docs.github.com/en/rest/reference/repos#branches)
image

Waiting from go-github to create a release on this PR:

google/go-github#2256

### CODE REVIEW

**Comment by diogopms** [comment]
This PR is blocked by updating the github-go library and support the field (https://github.com/google/go-github/issues/2255)

**Comment by kfcampbell** [comment]
@diogopms I've merged the latest `main` in, and chosen to default `allow_forking` to true, which I believe matches the behavior shown in the API docs you linked above. 

Are you okay with these changes as-is? If so, I can get them merged. If not, let's talk about it!

**Comment by diogopms** [comment]
👍🏻  looks good let's merge it , thanks for fixing it 🙏🏻

**Comment by jaredfholgate** [comment]
@kfcampbell and @diogopms This change is exhibiting odd behaviour and may need to be fixed or reverted. As per issue #1136. Also, for some reason the website docs have not been updated to reflect this new field, even though they are changed in this push. Happy to help if I can?

**Comment by kfcampbell** [comment]
@jaredfholgate I've reverted this PR and published [v4.24.1](https://github.com/integrations/terraform-provider-github/releases/tag/v4.24.1) with only that change in it. If you'd like to take a stab at fixing the behavior, I'd be happy to review it!

**Comment by martinm82** [comment]
What would be the desired behaviour? Should the implementation first check whether forking has been disabled on org level and in such a case do nothing? Is that feasible? I am not familiar with this provider but would really like to have the allow_forking support in the provider.

**Pull request merged**
