### PR TITLE
Upgrade go-github to v39

### PR DESCRIPTION
**Pull request by lauraseidler**
This should allow moving forward with #649 (I'll provide another PR). 

Release: https://github.com/google/go-github/releases/tag/v39.0.0 - the only breaking changes are in relation to [`ListRepositoryAccessRunnerGroup`](https://github.com/google/go-github/pull/2086), which this provider isn't using as far as I can see. 

Note: I'm not really a Go pro, so in case I messed something up, please let me know so I can learn :)

### CODE REVIEW

**Review by kfcampbell — APPROVED** [review]
This looks reasonable to me!

**Comment by xun-guo-anzx** [comment]
Hi @lauraseidler, with [this change](https://github.com/integrations/terraform-provider-github/issues/821) in release 4.15.0, I think [ListRepositoryAccessRunnerGroup](https://github.com/google/go-github/pull/2086) is referenced in [resource_github_actions_runner_group](https://github.com/integrations/terraform-provider-github/blob/main/github/resource_github_actions_runner_group.go#L172). I assume this needs to be updated now?

**Comment by lauraseidler** [comment]
Yeah, looks like it. Though I'm unsure what to pass there - I guess technically, this call should be looped to make sure to fetch all pages? 

Or we pass the default from GitHub (30 per page, page 1), as that would keep the current behaviour as is, and then full pagination can be implemented separately?

Thoughts @xun-guo-anzx?

**Comment by kfcampbell** [comment]
@xun-guo-anzx what's the behavior if `nil` is passed for options to `ListRepositoryAccessRunnerGroup`?

**Comment by xun-guo-anzx** [comment]
> @xun-guo-anzx what's the behavior if `nil` is passed for options to `ListRepositoryAccessRunnerGroup`?

It should work the same as current behaviour, which only fetches the first 30 repository from the list

**Comment by lauraseidler** [comment]
I've rebased this now and am passing `nil` to `ListRepositoryAccessRunnerGroup` here: https://github.com/integrations/terraform-provider-github/pull/905/files#diff-3a784b7896a69029f7895122c10d1858ade59409457828a7c3f4e0a17ae1207aR172

Personally, I would stick to this as the scope of this PR, as it should keep the behaviour exactly the same as before and only does the update, which should unblock both #649 and also implementing pagination for this in a follow up PR.

Does that work @xun-guo-anzx @kfcampbell?

**Comment by kfcampbell** [comment]
Yep that sounds good to me!

**Review by jcudit — APPROVED** [review]

**Pull request merged**
