### PR TITLE
fix(resource_github_repository): Create repo from template with visibility to avoid org policy issue

### LINKED ISSUE #925: Failed setting visibility=internal on a newly created repo from template
Hi there,

### Terraform Version
`1.0.5`

### Affected Resource(s)
- github_repository

### Terraform Configuration Files
```hcl
# create github repository for the domain under domain team
resource "github_repository" "domain" {
  name = lower("${var.domain}-domain")

  visibility = "internal"

  template {
    owner      = "our-enterprise-org-id"
    repository = "tf-domain-template"
  }
}
```

### Debug Output
Gist: https://gist.github.com/damir-dezeljin/e9de28e11aa7de8d7a60fc2e123794f6

**NOTE:** I removed the sensible parts from the logs. Still, I think the logs shows what's the actual issue.  Let me recap it here:

- We're using TF to create a GitHub repo out of a template.
- The template repo visibility is set to `Internal`.
- The newly created repo visibility should be `Internal` as well.
- The repo gets created, but it remains `Private` and the visibility setup phase fails with error 422.

### Panic Output
n/a

### Expected Behavior
I'd expect a new repo with visibility `Internal` being created.

### Actual Behavior
The `terraform apply` fails with error code `422` on visibility change step.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Set org policy to prevent users from changing repos visibility.
2. Create a template repo with visibility `Internal`
3. Use the provided TF code for creating a new repo with visibility `Internal` out of the template one.
4. Use a GitHub App identity with scopes listed below.
5. Run `terraform apply`.

### Important Factoids
- We're running TF with GitHub Apps credentials with following scopes:
  - Repository access: All repositories
  - Repository permissions:
    - Administration: r/w
    - Contents: r/w
    - Metadata: ro
    - Secrets: r/w
  - Organization permissions:
    - Members: r/w
    - Administration: r/w
- Our Enterprise has an Org.Policy set that prevents users from creating Public repos, as well only Org.Owners are allowed to change repos visibility.

### References
n/a

### PR DESCRIPTION
**Pull request by littlelionking**
Resolves #925 

----

### Before the change?

When creating a repository from a template, it sets the visibility to either `public` or `private` according to this bool:
```
Private:            github.Bool(isPrivate),
```
And then edits the repo settings later to ensure the visibility is correct.

### After the change?

Now it sets the `Visibility` parameter instead, allowing "internal" as an option.

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [x] No

----

### CODE REVIEW

**Comment by littlelionking** [comment]
I didn't see a way to set `Allow members to change repository visibilities for this organization.`  for tests and so I did not add any tests.

**Comment by littlelionking** [comment]
Hi @kfcampbell would I be able to get your thoughts on this?

**Review by nickfloyd — CHANGES_REQUESTED** [review]
Hey @littlelionking,

Given this resource is core to this provider we're going to need automated tests.  Also, please add [documentation](https://github.com/integrations/terraform-provider-github/blob/main/website/docs/r/repository.html.markdown) for the repo resource when you get the chance.

**Comment by littlelionking** [comment]
> Hey @littlelionking,
> 
> Given this resource is core to this provider we're going to need automated tests. Also, please add [documentation](https://github.com/integrations/terraform-provider-github/blob/main/website/docs/r/repository.html.markdown) for the repo resource when you get the chance.

Closed my PR as I am not likely to work on this. Would you be fine with this but replacing "private" with "internal?"
https://github.com/integrations/terraform-provider-github/blob/e6660d4fd3b75b743ec00b8432f1a4a912154da5/github/resource_github_repository_test.go#L1518-L1566

**Pull request closed without merging**
