### PR TITLE
Allow setting owner in anonymous mode

### LINKED ISSUE #647: terraform-import failure: Cannot import non-existent remote object
### Terraform Version
Terraform v0.14.3
provider "registry.terraform.io/hashicorp/github" { version     = "4.1.0" }

### Affected Resource(s)
- github_repository

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 0.14.0"

  backend "remote" {
    organization = "femiwiki"

    workspaces {
      name = "github"
    }
  }

  required_providers {
    github = {
      source  = "hashicorp/github"
      version = "~> 4.0"
    }
  }
}

provider "github" {
  organization = "femiwiki"
}
```

```hcl
resource "github_repository" "legunto" {
  name = "legunto"
  ...
}
```
Full configuration: https://github.com/femiwiki/infra/blob/50eb0673787a8cab88041876632e45b6df6a2a57/github/repo.tf#L465-L472

### Debug Output
https://gist.github.com/lens0021/35d5e8997a389bfcd91fa6cc976d2fbc

### Expected Behavior

A state which is created based on https://github.com/femiwiki/legunto is Imported successfully.

### Actual Behavior

"Error: Cannot import non-existent remote object" is printed. See the debug output for details.

### Steps to Reproduce

1. Uncomment https://github.com/femiwiki/infra/blob/50eb0673787a8cab88041876632e45b6df6a2a57/github/repo.tf#L465-L472
1. `terraform import github_repository.legunto legunto`

### Important Factoids

Our team is using Terraform Cloud (https://app.terraform.io/).

### PR DESCRIPTION
**Pull request by kfcampbell**
Fixes #647. 

The provider currently doesn't respect any ownership configuration when running in anonymous mode. This is annoying because it blocks all kinds of uses, for example data sources retrieving public repos. 

This PR makes a small change to respect ownership in anonymous mode, and now those data sources work!

### CODE REVIEW

**Comment by kfcampbell** [comment]
cc @Olin-Vorechovsky I'd rather do this than error if there's no token present, since there's a lot of valid use cases for the provider without auth configured IMO. Thoughts?

**Comment by kfcampbell** [comment]
I think this is a worthwhile change and since it's not breaking backwards compatibility, I've added it to a future milestone for release.

**Comment by kfcampbell** [comment]
@jcudit let's talk about this in the next week or two!

**Comment by nickfloyd** [comment]
👋 Hey Friends, this issue has been automatically marked as stale because it has no recent activity. It will be closed if no further activity occurs. Please add the `Status: Pinned` label if you feel that this issue needs to remain open/active. Thank you for your contributions and help in keeping things tidy!

**Comment by kfcampbell** [comment]
I had forgotten about this! I think this is still relevant and should be merged.

**Pull request merged**
