### PR TITLE
feat: Support rule type code_scanning 

### LINKED ISSUE #2310: [FEAT]: support rule type code_scanning for github_organization_ruleset
### Describe the need

Would be great to be able to enable rules.code_scanning within the github_organization_ruleset and github_repository_ruleset resources.

image

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ihor-hrytskiv**
Support rule type code_scanning for github_organization_ruleset and github_repository_ruleset

Resolves #2310

Example:

```hcl
data "github_repository" "workflow_repo" {
    name = "workflow_repo"
}

resource "github_organization_ruleset" "org_ruleset" {
    name        = "example"
    target      = "branch"
    enforcement = "active"

    rules {
        required_code_scanning {
            required_code_scanning_tool {
                alerts_threshold          = "errors"
                security_alerts_threshold = "high_or_higher"
                tool                      = "CodeQL"
            }
        }
    }
}

resource "github_repository_ruleset" "repo_ruleset" {
    name        = "example"
    repository  = data.github_repository.workflow_repo.name
    target      = "branch"
    enforcement = "active"

    rules {
        required_code_scanning {
            required_code_scanning_tool {
                alerts_threshold          = "errors"
                security_alerts_threshold = "high_or_higher"
                tool                      = "CodeQL"
            }
        }
    }
}
```

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Comment by kfcampbell** [comment]
@ihor-hrytskiv would it be possible to split out the `google/go-github` v66 upgrade to a separate PR? It makes it easier to roll back if something goes wrong with either part of the change, which we've had happen before.

**Comment by ihor-hrytskiv** [comment]
> Resolves #2310

Thank @kfcampbell for suggestion, [this](https://github.com/integrations/terraform-provider-github/pull/2443) my PR

**Comment by kfcampbell** [comment]
@ihor-hrytskiv I merged your other PR and gave a shot at a merge from there into here. It looks like there's some issues with deprecated routes and linting errors, though that could be my fault from the merge. Thoughts?

**Comment by ihor-hrytskiv** [comment]
> @ihor-hrytskiv I merged your other PR and gave a shot at a merge from there into here. It looks like there's some issues with deprecated routes and linting errors, though that could be my fault from the merge. Thoughts?

@kfcampbell fixed

**Review by kfcampbell — APPROVED** [review]
@ihor-hrytskiv thank you!

**Pull request merged**
