### PR TITLE
Adding missing RequiresLinearHistory

### PR DESCRIPTION
**Pull request by jtyr**
This PR is adding missing parameter that sets the `required_linear_history` in the branch protection. Without this patch, I can don't see the `requiresLinearHistory` in the request data:

```
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: 2021/10/08 14:21:23 [DEBUG] Github API Request Details:
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: ---[ REQUEST ]---------------------------------------
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: POST /graphql HTTP/1.1
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: Host: api.github.com
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: User-Agent: Go-http-client/1.1
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: Content-Length: 665
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: Content-Type: application/json
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: Accept-Encoding: gzip
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: 
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: {
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:  "query": "mutation($input:UpdateBranchProtectionRuleInput!){updateBranchProtectionRule(input: $input){branchProtectionRule{id}}}",
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:  "variables": {
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:   "input": {
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "branchProtectionRuleId": "BPR_kwDOGLwnv84BVkxt",
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "pattern": "release",
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "requiresApprovingReviews": true,
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "requiredApprovingReviewCount": 1,
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "requiresCommitSignatures": false,
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "allowsForcePushes": false,
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "allowsDeletions": false,
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "isAdminEnforced": true,
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "requiresStatusChecks": false,
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "requiresStrictStatusChecks": false,
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "requiresCodeOwnerReviews": false,
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "dismissesStaleReviews": false,
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "restrictsReviewDismissals": false,
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "reviewDismissalActorIds": null,
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "restrictsPushes": false,
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "pushActorIds": null,
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "requiredStatusCheckContexts": null
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:   }
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:  }
2021-10-08T14:21:23.703+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: }
```

With this patch, I can see the `requiresLinearHistory` in the request data:

```
2021-10-08T14:11:47.287+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: 2021/10/08 14:11:47 [DEBUG] Github API Request Details:
2021-10-08T14:11:47.287+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: ---[ REQUEST ]---------------------------------------
2021-10-08T14:11:47.287+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: POST /graphql HTTP/1.1
2021-10-08T14:11:47.287+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: Host: api.github.com
2021-10-08T14:11:47.287+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: User-Agent: Go-http-client/1.1
2021-10-08T14:11:47.287+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: Content-Length: 694
2021-10-08T14:11:47.287+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: Content-Type: application/json
2021-10-08T14:11:47.287+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: Accept-Encoding: gzip
2021-10-08T14:11:47.287+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: 
2021-10-08T14:11:47.287+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: {
2021-10-08T14:11:47.287+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:  "query": "mutation($input:UpdateBranchProtectionRuleInput!){updateBranchProtectionRule(input: $input){branchProtectionRule{id}}}",
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:  "variables": {
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:   "input": {
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "branchProtectionRuleId": "BPR_kwDOGLwnv84BVkxt",
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "pattern": "release",
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "requiresApprovingReviews": true,
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "requiredApprovingReviewCount": 1,
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "requiresCommitSignatures": false,
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "requiresLinearHistory": true,
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "allowsForcePushes": false,
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "allowsDeletions": false,
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "isAdminEnforced": true,
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "requiresStatusChecks": false,
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "requiresStrictStatusChecks": false,
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "requiresCodeOwnerReviews": false,
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "dismissesStaleReviews": false,
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "restrictsReviewDismissals": false,
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "reviewDismissalActorIds": null,
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "restrictsPushes": false,
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "pushActorIds": null,
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:    "requiredStatusCheckContexts": null
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:   }
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0:  }
2021-10-08T14:11:47.288+0100 [DEBUG] provider.terraform-provider-github_v4.16.0: }
```

### CODE REVIEW

**Review by majormoses — APPROVED** [review]
LGTM

**Review by jcudit — APPROVED** [review]
Thanks for the patience on this one 🙇🏾 

Looks good to ship! @jtyr can I get some help with the conflicts?

**Comment by jtyr** [comment]
@jcudit Code rebase.

**Comment by philippeboyd** [comment]
It seems to be missing a final approval from @majormoses

**Comment by majormoses** [comment]
> It seems to be missing a final approval from @majormoses

Just a contributor. Will need assistance from @jcudit or another maintainer.

**Review by jcudit — APPROVED** [review]

**Pull request merged**
