### PR TITLE
bugfix: include empty Checks array on v3 branch protection creation

### LINKED ISSUE #1307: Cannot create github_branch_protection_v3 after update to v5.3.0
### Terraform Version
**v5.3.0**

### Affected Resource(s)

- github_branch_protection_v3
- github_branch_default
- github_branch_default

The issue occures when creating a new `github_branch_protection_v3` resource with attributes referenced from `github_branch_default` and `github_branch_protection_v3` resources.

### Debug Output

```
github_branch_protection_v3.<MY_REPO_NAME_REDACTED>: Creating...
╷
│ Error: PUT https://api.github.com/repos/<MY_ORG_REDACTED>/<MY_REPO_NAME_REDACTED>/branches/main/protection: 422 Invalid request.
│
│ No subschema in "anyOf" matched.
│ For 'properties/checks', nil is not an array.
│ Not all subschemas of "allOf" matched.
│ For 'anyOf/1', {"strict"=>true, "contexts"=>["build"], "checks"=>nil} is not a null. []
```

### Expected Behavior
The branch protection v3 resource should be created.

### Actual Behavior
Terraform errors out with message above.

#### Step 1

Create a repo with terraform apply.

```
resource "github_repository" "test-repo" {
  name        = "test-repo"
  description = "This repo is a test"

  has_downloads = true
  has_issues    = false
  has_projects  = false
  has_wiki      = false

  visibility = "private"

  auto_init = true

  vulnerability_alerts = false
}

resource "github_branch_default" "test-repo" {
  repository = github_repository.test-repo.name
  branch     = "main"
}
```

#### Step 2

Terraform apply the following change:

```
resource "github_branch_protection_v3" "test-repo" {
  repository     = github_repository.test-repo.name
  branch         = github_branch_default.test-repo.branch
  enforce_admins = true

  required_status_checks {
    strict   = true
    contexts = ["build"]
  }

  required_pull_request_reviews {
    dismiss_stale_reviews      = true
    require_code_owner_reviews = true
  }
}
```

### Important Factoids
This works up to GitHub provider version v5.2.0 without errors and errors in v5.3.0.

This seems to be linked to the go client update in the [release diff](https://github.com/integrations/terraform-provider-github/compare/v5.2.0...v5.3.0)  where the API Client is updated as follows.

https://github.com/integrations/terraform-provider-github/blob/6773d80600f761bf50b695f475c2d457d1151ee5/vendor/github.com/google/go-github/v47/github/repos.go#L908

From 

```
Checks []*RequiredStatusCheck `json:"checks,omitempty"
```

To

```
Checks []*RequiredStatusCheck `json:"checks"`
```

### References
- https://github.com/integrations/terraform-provider-github/releases

### PR DESCRIPTION
**Pull request by TheQueenIsDead**
Resolves #1307 #1147

----

### Before the change?

* Branch protections can not be created due to a nil error on the upstream Github API.

### After the change?

* The nil value is now passed as an empty array which causes the branch protection to be applied successfully.

### Other information

* Aims to resolve this issue https://github.com/integrations/terraform-provider-github/issues/1307 by implementing the upstream suggestion for resolution as proposed here https://github.com/google/go-github/issues/2467#issuecomment-1250072559

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by TheQueenIsDead** [comment]
I don't seem to be able to add a label to it, but this would be a `Type: Bug` PR :+1:

**Comment by kfcampbell** [comment]
@TheQueenIsDead this approach sounds reasonable to me! Please let me know if you have any issues testing this. I'm looking forward to getting it merged!

**Comment by TheQueenIsDead** [comment]
I setup a test file like so for the following repository https://github.com/TheDeadPoetSociety/terraform-template-module:

```terraform
resource "github_branch_protection_v3" "bp" {

  repository = "terraform-template-module"
  branch     = "master"


  enforce_admins = true
  required_pull_request_reviews {
    dismiss_stale_reviews = true
  }
  required_status_checks  {
    strict = false
    contexts = []
  }
}

terraform {
  required_providers {
    github = {
      source = "integrations/github"
    }
  }
}

provider "github" {
  # Configuration options
  owner = "TheDeadPoetSociety"
  token = "github_pat_XYZ"
}
```

When I ran the following I received the expected error:
```console
$ go build -o ~/go/bin/
$ terraform init -upgrade

Initializing the backend...

Initializing provider plugins...
- Finding latest version of integrations/github...
- Using previously-installed integrations/github v5.11.0

Terraform has been successfully initialized!
...

$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # github_branch_protection_v3.bp will be created
  + resource "github_branch_protection_v3" "bp" {
      + branch                          = "master"
      + enforce_admins                  = true
      + etag                            = (known after apply)
      + id                              = (known after apply)
      + repository                      = "terraform-template-module"
      + require_conversation_resolution = false
      + require_signed_commits          = false

      + required_pull_request_reviews {
          + dismiss_stale_reviews           = true
          + required_approving_review_count = 1
        }

      + required_status_checks {
          + strict = false
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

github_branch_protection_v3.bp: Creating...
╷
│ Error: PUT https://api.github.com/repos/TheDeadPoetSociety/terraform-template-module/branches/master/protection: 422 Invalid request.
│ 
│ No subschema in "anyOf" matched.
│ For 'properties/checks', nil is not an array.
│ Not all subschemas of "allOf" matched.
│ For 'anyOf/1', {"strict"=>false, "checks"=>nil} is not a null. []
│ 
│   with github_branch_protection_v3.bp,
│   on main.tf line 4, in resource "github_branch_protection_v3" "bp":
│    4: resource "github_branch_protection_v3" "bp" {
│ 
╵
```

When I ran a plan with my local version, the apply worked:
```console
$ go build -o ~/go/bin/
$ TF_CLI_CONFIG_FILE=/home/david/GolandProjects/terraform-provider-github/examples/dev.tfrc terraform apply
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - integrations/github in /home/david/go/bin
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # github_branch_protection_v3.bp will be created
  + resource "github_branch_protection_v3" "bp" {
      + branch                          = "master"
      + enforce_admins                  = true
      + etag                            = (known after apply)
      + id                              = (known after apply)
      + repository                      = "terraform-template-module"
      + require_conversation_resolution = false
      + require_signed_commits          = false

      + required_pull_request_reviews {
          + dismiss_stale_reviews           = true
          + required_approving_review_count = 1
        }

      + required_status_checks {
          + strict = false
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

github_branch_protection_v3.bp: Creating...
github_branch_protection_v3.bp: Creation complete after 4s [id=terraform-template-module:master]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

Cool to see! 
The resulting protection in Github looks like this:
image
image


I also tested creating the resource with the latest provider and updating the required_status_checks with the local provider thereafter
```console
$ go build -o ~/go/bin/
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # github_branch_protection_v3.bp will be created
  + resource "github_branch_protection_v3" "bp" {
      + branch                          = "master"
      + enforce_admins                  = true
      + etag                            = (known after apply)
      + id                              = (known after apply)
      + repository                      = "terraform-template-module"
      + require_conversation_resolution = false
      + require_signed_commits          = false

      + required_pull_request_reviews {
          + dismiss_stale_reviews           = true
          + required_approving_review_count = 1
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

github_branch_protection_v3.bp: Creating...
github_branch_protection_v3.bp: Creation complete after 4s [id=terraform-template-module:master]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
$ # Uncomment required_status_checks
$ TF_CLI_CONFIG_FILE=/home/david/GolandProjects/terraform-provider-github/examples/dev.tfrc terraform apply
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - integrations/github in /home/david/go/bin
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
github_branch_protection_v3.bp: Refreshing state... [id=terraform-template-module:master]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # github_branch_protection_v3.bp will be updated in-place
  ~ resource "github_branch_protection_v3" "bp" {
        id                              = "terraform-template-module:master"
        # (6 unchanged attributes hidden)

      + required_status_checks {
          + strict = false
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

github_branch_protection_v3.bp: Modifying... [id=terraform-template-module:master]
github_branch_protection_v3.bp: Modifications complete after 4s [id=terraform-template-module:master]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed. 

```


I also tested creating branch protections without specifying `contexts` at all, and adding strict = true to pre-existing protections. Worked well without any mention of contexts :+1:

**Comment by TheQueenIsDead** [comment]
Ah, it does fall flat when an apply is made with the new provider and the checks array is not null :-( 

```
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # github_branch_protection_v3.bp will be created
  + resource "github_branch_protection_v3" "bp" {
      + branch                          = "master"
      + enforce_admins                  = true
      + etag                            = (known after apply)
      + id                              = (known after apply)
      + repository                      = "terraform-template-module"
      + require_conversation_resolution = false
      + require_signed_commits          = false

      + required_pull_request_reviews {
          + dismiss_stale_reviews           = true
          + required_approving_review_count = 1
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

github_branch_protection_v3.bp: Creating...
github_branch_protection_v3.bp: Creation complete after 3s [id=terraform-template-module:master]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

$ TF_CLI_CONFIG_FILE=/home/david/GolandProjects/terraform-provider-github/examples/dev.tfrc terraform apply
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - integrations/github in /home/david/go/bin
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
github_branch_protection_v3.bp: Refreshing state... [id=terraform-template-module:master]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # github_branch_protection_v3.bp will be updated in-place
  ~ resource "github_branch_protection_v3" "bp" {
        id                              = "terraform-template-module:master"
        # (6 unchanged attributes hidden)

      + required_status_checks {
          + contexts = [
              + "example",
            ]
          + strict   = true
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

github_branch_protection_v3.bp: Modifying... [id=terraform-template-module:master]
╷
│ Error: PUT https://api.github.com/repos/TheDeadPoetSociety/terraform-template-module/branches/master/protection: 422 Invalid request.
│ 
│ No subschema in "anyOf" matched.
│ More than one subschema in "oneOf" matched.
│ Not all subschemas of "allOf" matched.
│ For 'anyOf/1', {"strict"=>true, "contexts"=>["example"], "checks"=>[]} is not a null. []
│ 
│   with github_branch_protection_v3.bp,
│   on main.tf line 4, in resource "github_branch_protection_v3" "bp":
│    4: resource "github_branch_protection_v3" "bp" {
│ 
╵

**Comment by TheQueenIsDead** [comment]
I'm starting to understand that the issue seems to be that both `Contexts` and `Checks` can not be defined. The issue is that we can not fully ommit `Checks` given the removal of the `omitempty` flag, it always defaults to an empty array, even if the client specifies `nil`:
https://github.com/integrations/terraform-provider-github/blob/main/vendor/github.com/google/go-github/v48/github/repos.go#L985
```go
type RequiredStatusChecks struct {
	// Require branches to be up to date before merging. (Required.)
	Strict bool `json:"strict"`
	// The list of status checks to require in order to merge into this
	// branch. (Deprecated. Note: only one of Contexts/Checks can be populated,
	// but at least one must be populated).
	Contexts []string `json:"contexts,omitempty"`
	// The list of status checks to require in order to merge into this
	// branch.
	Checks []*RequiredStatusCheck `json:"checks"`
}
```

 I thought I was being smart with the empty array, but the existence of both keys is the issue :-( 
 
 @kfcampbell , I have had success with using the provided "contexts" array and creating `Checks` instead, but this seems a bit hacky, as an example:
```go
func expandRequiredStatusChecks(d *schema.ResourceData) (*github.RequiredStatusChecks, error) {
	if v, ok := d.GetOk("required_status_checks"); ok {
		vL := v.([]interface{})
		if len(vL) > 1 {
			return nil, errors.New("cannot specify required_status_checks more than one time")
		}
		rsc := new(github.RequiredStatusChecks)

		for _, v := range vL {
			// List can only have one item, safe to early return here
			if v == nil {
				return nil, nil
			}
			m := v.(map[string]interface{})
			rsc.Strict = m["strict"].(bool)

			contexts := expandNestedSet(m, "contexts")
                        // Iterate the provided "contexts" but pass them to the SDK as contexts with default app_id's
			rsc.Checks = func() []*github.RequiredStatusCheck {
				var checks []*github.RequiredStatusCheck
				for _, c := range contexts {
					checks = append(checks, &github.RequiredStatusCheck{
						Context: c,
						AppID:   nil,
					})
				}
				return checks
			}()
		}
		return rsc, nil
	}

	return nil, nil
}
```
 
 Would the best solution be to implement full support for contexts like how k24dizzle was going to do before he got blocked on the upstream provider? (This PR for reference: https://github.com/integrations/terraform-provider-github/pull/1051)
 
If so I will close this PR for the moment and perhaps see if I can take-over where they left off :+1:

**Comment by TheQueenIsDead** [comment]
This workaround was worth trying, but I think the best thing to do would be to support `checks`.

I have opened up a WIP PR to implement this here: https://github.com/integrations/terraform-provider-github/pull/1415

**Pull request closed without merging**
