### PR TITLE
Add note documenting org owners' team membership behavior

### LINKED ISSUE #1046: github_team_member are always "maintainers" on first apply
### Terraform Version

```
# terraform -v
Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/github v4.19.2

Your version of Terraform is out of date! The latest version
is 1.1.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)
- github_team_membership

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
variable "members" {
  type = set(string)
  default = [
    "jkamenik", # me
  ]
}

resource "github_team" "test" {
  name    = "test-group"
  privacy = "closed"
}

resource "github_team_membership" "member" {
  for_each = var.members

  team_id  = github_team.test.id
  username = each.value
  role     = "member" # doesn't matter if this is explicit or not
}
```

### Expected Behavior
That the user are added as "members"

### Actual Behavior
The users are added as "maintainers" the first time.  Then you have to turn a second plan and apply to make them "members".  You can see this by running a plan right after the first apply.

```
terraform apply
...

terraform plan
...
Terraform will perform the following actions:

  # module.test-members.github_team_membership.member["jkamenik"] will be updated in-place
  ~ resource "github_team_membership" "member" {
        id       = "5591725:jkamenik"
      ~ role     = "maintainer" -> "member"
        # (3 unchanged attributes hidden)
    }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` - They were made maintainers
2. `terraform plan --out my.plan` - This will show the issues
3. `terraform apply my.plan` - Fixes the issues

### PR DESCRIPTION
**Pull request by kfcampbell**
Resolves #1046.

----

### Before the change?

* Many users had confusion about a perpetual diff being generated by attempting to set an organization owner to team "member" rather than "maintainer". 

### After the change?

* Our documentation for both the team_members and team_membership resources includes a note about what happens when attempting to set an organization owner to team "member". 

### Other information

* See #1046 for more context. 

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [X] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by jcogilvie** [comment]
I believe the diff will show you changing them *to* member on all subsequent applies, since maintainer is the response that gets saved into state from the API response, but member is the code.

**Comment by kfcampbell** [comment]
@jcogilvie thank you for the suggestion. Do you have a phrasing suggestion? I'd happily commit a suggestion if offered.

**Comment by jcogilvie** [comment]
Maybe this?

~> Attempting to set a user who is an organization owner to "member" will result in the user being granted "maintainer" instead; this can result in a perpetual `terraform plan` diff that changes their status back to "member".

**Comment by kfcampbell** [comment]
@jcogilvie thanks for the suggestion! I've implemented it as written.

**Pull request merged**
