### PR TITLE
[Feature] Add data source to read secrets

### PR DESCRIPTION
**Pull request by bpaquet**

### CODE REVIEW

**Comment by bpaquet** [comment]
@kfcampbell Any way to review this ? Thx

**Comment by kfcampbell** [comment]
Does github/data_source_github_actions_secrets.go track repository-level secrets? It's not immediately clear to me how that's different from organization secrets and dependabot secrets.

**Comment by bpaquet** [comment]
> Does github/data_source_github_actions_secrets.go track repository-level secrets? It's not immediately clear to me how that's different from organization secrets and dependabot secrets.

Yes it is. I followed the naming we already have on resources.

**Review by kfcampbell — APPROVED** [review]
Thank you for contributing!

**Pull request merged**
