### PR TITLE
fix(r/repository): suppress `etag` changes

### PR DESCRIPTION
**Pull request by jcudit**
/cc https://github.com/integrations/terraform-provider-github/issues/796

### CODE REVIEW

**Review by kfcampbell — APPROVED** [review]
I haven't been able to reproduce the changing `etag` issue recently with several repository creations. That being said, I can't remember ever caring about the `etag` output and it's good with me to suppress it by default.

**Comment by k24dizzle** [comment]
Is anyone else running into this following error? 

```
Error: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
	* resource github_repository: etag: DiffSuppressFunc is for suppressing differences between config and state representation. There is no config for computed-only field, nothing to compare.
```

**Comment by starhawking** [comment]
> Is anyone else running into this following error?
> 
> ```
> Error: Internal validation of the provider failed! This is always a bug
> with the provider itself, and not a user issue. Please report
> this bug:
> 
> 1 error occurred:
> 	* resource github_repository: etag: DiffSuppressFunc is for suppressing differences between config and state representation. There is no config for computed-only field, nothing to compare.
> ```

I just ran into this myself! Everything worked again when I backed out this change

**Comment by starhawking** [comment]
Is there a reason testing was turned off for releases? There isn't much in the commit message when it was turned off, and they caught this error

https://github.com/integrations/terraform-provider-github/commit/554df9fc34c56dd74c77e237bfd12beac803b529

```
=== RUN   TestProvider/has_an_implementation
--- FAIL: TestProvider (0.00s)
    --- FAIL: TestProvider/runs_internal_validation_without_error (0.00s)
    --- PASS: TestProvider/has_an_implementation (0.00s)
```

**Pull request merged**
