### PR TITLE
Create data source for github app

### PR DESCRIPTION
**Pull request by g-chouzadjian**
- Adding support for returning information about a GitHub app.
- This feature enables the scenario where you'd like an app to be part of the push restrictions list for a branch protection rule.

### CODE REVIEW

**Comment by g-chouzadjian** [comment]
Addresses https://github.com/integrations/terraform-provider-github/issues/1009

**Comment by Luis-3M** [comment]
+1

**Comment by KnechtionsCoding** [comment]
@g-chouzadjian Is there a plan to try to get this released?

**Comment by g-chouzadjian** [comment]
@KnechtionsCoding not sure how to progress this - I was just waiting on a review from codeowners ⌛

**Review by kfcampbell — APPROVED** [review]
I've merged in main and made some small fixes to the documentation. This will be released soon!

**Pull request merged**
