### PR TITLE
Add environment resource support

### PR DESCRIPTION
**Pull request by d8x**
Support for creating/updating/deleting repo environments. Implemented with the v3 github client and direct use of github RestAPI. This should address #528.

### CODE REVIEW

**Comment by nadenf** [comment]
@d8x .. Any reason you closed this ?

**Comment by srgustafson8** [comment]
@d8x indeed - this looked good. Anything I can help with?

**Comment by d8x** [comment]
hey! @srgustafson8 this was done for an interview request. The outcome was that the implementation is not good so I closed the PR as I'm a bit busy currently with other things and cannot finish it. If you want please just copy the PR and add it!

**Comment by srgustafson8** [comment]
@d8x oh, no worries! hope the interview went well regardless. I'll see if I can pick this up where you left off.

**Pull request closed without merging**
