### PR TITLE
Add prevent_self_review parameter to the github_repository_environment resource

### PR DESCRIPTION
**Pull request by Nmishin**
Resolves  https://github.com/integrations/terraform-provider-github/issues/1967

### Before the change?
*  We can't manage "Prevent self-review" option

### After the change?
* We can manage "Prevent self-review" option

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Comment by kfcampbell** [comment]
#2011 will unblock this PR.

**Comment by andreas-aman** [comment]
I saw #2011 has been superseeded by #2081 that has been merged. Does this mean this PR can be unblocked?

**Comment by Nmishin** [comment]
@kfcampbell MR updated, could you please review

**Review by kfcampbell — APPROVED** [review]
Confirming integration tests are passing for me. Thank you for the contribution!

**Pull request merged**
