### PR TITLE
Add support for packages IP ranges in github_ip_ranges

### PR DESCRIPTION
**Pull request by Nmishin**
Resolves https://github.com/integrations/terraform-provider-github/issues/1812

Can be merged after go-github change: https://github.com/google/go-github/pull/2964

----

### Before the change?

* 

### After the change?

* 

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Comment by kfcampbell** [comment]
We're waiting here on the next release of google/go-github. Thanks for the contribution!

**Comment by Nmishin** [comment]
@kfcampbell could you please review, i think we are ready to merge it

**Comment by kfcampbell** [comment]
Would you mind adding appropriate checks for these fields in github/data_source_github_ip_ranges_test.go?

**Comment by Nmishin** [comment]
Test updated!

**Review by kfcampbell — APPROVED** [review]
@Nmishin Awesome, thank you!

**Pull request merged**
