### PR TITLE
fix: verify & set parent team after creation

### LINKED ISSUE #1167: team with parent_team_id created at root of org
Hi,

I am creating a child team using Github app authentication.

### Terraform Version
terraform: `1.2.1`
github provider: 4.26.0

### Affected Resource(s)
Please list the resources as a list, for example:
- `github_team`

### Terraform Configuration Files
```
resource "github_team" "this" {
  for_each = var.create_github_teams ? { for k, v in local.raw_new_teams : k => v if v.github.create == "true" } : {}
  name     = each.value.github_curent_name == "" ? each.value.team_name : each.value.github_curent_name # should use `team_name` when renaming is done
  #description              = format("%s %s %s", each.value.full_name, each.value.description, each.value.slack_channel) # us when renaming
  description               = format("%s\n%s", each.value.description, local.terraform_disclaimer)
  privacy                   = "closed"
  create_default_maintainer = false # setting to true adds creating user as maintainer to all teams
  parent_team_id            = lookup(local.team_to_id, each.value.github.parent_team, null)
}
```

Plan looks ok
```
  # github_team.this["aaa-bbb"] will be created
  + resource "github_team" "this" {
      + create_default_maintainer = false
      + description               = <<-EOT
            <description>
        EOT
      + etag                      = (known after apply)
      + id                        = (known after apply)
      + members_count             = (known after apply)
      + name                      = "<team-slug>"
      + node_id                   = (known after apply)
      + parent_team_id            = <123456789>
      + privacy                   = "closed"
      + slug                      = (known after apply)
    }
```

The request looks good:
```
2022-05-31T11:52:10.319+0200 [DEBUG] provider.terraform-provider-github_v4.26.0: ---[ REQUEST ]---------------------------------------
2022-05-31T11:52:10.319+0200 [DEBUG] provider.terraform-provider-github_v4.26.0: POST /orgs/<org>/teams HTTP/1.1
2022-05-31T11:52:10.319+0200 [DEBUG] provider.terraform-provider-github_v4.26.0: Host: api.github.com
2022-05-31T11:52:10.319+0200 [DEBUG] provider.terraform-provider-github_v4.26.0: User-Agent: go-github
2022-05-31T11:52:10.319+0200 [DEBUG] provider.terraform-provider-github_v4.26.0: Content-Length: 144
2022-05-31T11:52:10.319+0200 [DEBUG] provider.terraform-provider-github_v4.26.0: Accept: application/vnd.github.v3+json
2022-05-31T11:52:10.319+0200 [DEBUG] provider.terraform-provider-github_v4.26.0: Content-Type: application/json
2022-05-31T11:52:10.319+0200 [DEBUG] provider.terraform-provider-github_v4.26.0: Accept-Encoding: gzip
2022-05-31T11:52:10.319+0200 [DEBUG] provider.terraform-provider-github_v4.26.0: 
2022-05-31T11:52:10.319+0200 [DEBUG] provider.terraform-provider-github_v4.26.0: {
2022-05-31T11:52:10.319+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "name": "<team-slug>",
2022-05-31T11:52:10.319+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "description": "\n<description>",
2022-05-31T11:52:10.319+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "parent_team_id": <123456789>,
2022-05-31T11:52:10.319+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "privacy": "closed"
2022-05-31T11:52:10.319+0200 [DEBUG] provider.terraform-provider-github_v4.26.0: }
```
But the response has `"parent": null`:
```
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0: {
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "name": "<team_slug>",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "id": <123456789>,
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "node_id": "T_kwDOAAy4jM4AXgFM",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "slug": "<team_slug>",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "description": "\nManaged by terraform at <org>/<repo>",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "privacy": "closed",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "url": "https://api.github.com/organizations/<org_id>/team/<123456789>",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "html_url": "https://github.com/orgs/<org>/teams/<team_slug>",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "members_url": "https://api.github.com/organizations/<org_id>/team/<123456789>/members{/member}",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "repositories_url": "https://api.github.com/organizations/<org_id>/team/<123456789>/repos",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "permission": "pull",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "parent": null,
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "created_at": "2022-05-31T09:52:10Z",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "updated_at": "2022-05-31T09:52:10Z",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "members_count": 0,
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "repos_count": 0,
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  "organization": {
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "login": "<org_login>",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "id": <org_id>,
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "node_id": "MDEyOk9yZ2FuaXphdGlvbjgzMzY3Ng==",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "url": "https://api.github.com/orgs/<org>",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "repos_url": "https://api.github.com/orgs/<org>/repos",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "events_url": "https://api.github.com/orgs/<org>/events",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "hooks_url": "https://api.github.com/orgs/<org>/hooks",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "issues_url": "https://api.github.com/orgs/<org>/issues",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "members_url": "https://api.github.com/orgs/<org>/members{/member}",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "public_members_url": "https://api.github.com/orgs/<org>/public_members{/member}",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "avatar_url": "https://avatars.githubusercontent.com/u/<org_id>?v=4",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "description": "The most flexible and powerful sales communication tool.",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "name": "<Name>",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "company": null,
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "blog": "<website>",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "location": "<city>",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "email": "<email>",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "twitter_username": null,
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "is_verified": false,
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "has_organization_projects": true,
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "has_repository_projects": true,
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "public_repos":,
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "public_gists": 0,
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "followers": 0,
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "following": 0,
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "html_url": "https://github.com/<org>",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "created_at": "2011-06-06T21:08:30Z",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "updated_at": "2022-04-21T15:41:41Z",
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:   "type": "Organization"
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0:  }
2022-05-31T11:52:10.823+0200 [DEBUG] provider.terraform-provider-github_v4.26.0: }
```

**If add a team under some temporary parent (but the team will still end up in root of the org) and then change this parent, terraform will create plan to update from one parent to another and then I can see the changes in the UI correctly. Plan:**
```
  # github_team.this["<team_slug>"] will be updated in-place
  ~ resource "github_team" "this" {
        id                        = "<team_id>"
        name                      = "<team_slug>"
      ~ parent_team_id            = 123456789 -> 987654321
        # (7 unchanged attributes hidden)
    }
```

### Debug Output
Debug output attached above. I can provider more if needed.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Team created under parent team.

### Actual Behavior
Team created at root level of the org.

### Steps to Reproduce
Create team with `parent_team_id` - team is created at root level without parent.

### Important Factoids
Using github application authentication.

### PR DESCRIPTION
**Pull request by reiniertimmer**
Resolves #1167

### Before the change?

Using a GitHub App, the parent team is not set (when the parent team was _not_ created by the GitHub App). Effectively, the created team will then be at the root level with a pending approval.

image

However, the GitHub App should be allowed to nest under parent teams, this just needs an additional call to the REST API [update team](https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#update-a-team) endpoint.

### After the change?

When adding a team with a `parent` team specified, it will now work the same with GitHub Apps as it works with PATs.

### Other information

This change only adds one check:

* if a parent was requested, but the nesting was _not_ created, this change will just re-attempt to create the nesting. This may still mean that the nesting will not be done properly.
* existing tests are only for testing the integration with a PAT. I did not add an additional case using a GitHub App. Maybe that's something can be done separately?

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Should not be a breaking change.

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

### Pull request type

- Bugfix: `Type: Bug`

### CODE REVIEW

**Comment by kfcampbell** [comment]
@reiniertimmer would you mind adding a brief code comment describing the need and circumstances around the extra call? I think I'll be confused when looking at this again in the future and a description may be helpful.

**Comment by reiniertimmer** [comment]
@kfcampbell of course I can do that. Will do that as soon as I have the opportunity.

I must say that the whole behavioural difference in the API is a bit unexpected.

The additional call to set the parent is also not guaranteed to succeed (permission-wise, even with a PAT) which makes this something of a best-effort attempt.

I'll see if I can catch that in a short but meaningful comment  😊

**Comment by kfcampbell** [comment]
> Is there anything that can be done to improve the testing with GitHub App tokens as well? Or is that effort already being started here? https://github.com/integrations/terraform-provider-github/issues/1414

The will to do so is there but unfortunately the effort hasn't been started yet. I agree that testing with GitHub Apps would be a great idea and it's something we should do in the future.

**Review by kfcampbell — APPROVED** [review]
I've confirmed that the relevant integration tests are still passing locally on this branch. I'll get this merged and released sometime in the near future; hopefully it'll help ease some of the errors users are seeing.

**Pull request merged**
