### PR TITLE
Add support for providing a GitHub app as a pull request bypasser

### PR DESCRIPTION
**Pull request by strideynet**
Potentially resolves https://github.com/integrations/terraform-provider-github/issues/1156

Replaces PR https://github.com/integrations/terraform-provider-github/pull/1202

----

### Before the change?

Configuring a GitHub App as a pull request bypasser will always state there is one change to make.

### After the change?

After applying the Terraform once, it will not show as a change again.

### Other information

Have a great day 🖖 

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

No

### Pull request type

Some might argue this is a bugfix, some might argue it's a new feature /shrug

Please add the corresponding label for change this PR introduces:
- Feature/model/API additions: `Type: Feature`

----

### Manual testing

I created an app named `test-tf-branch-protection`.

I applied: 
```tf
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
    }
  }
}

# Configure the GitHub Provider
provider "github" {}

resource "github_repository" "test" {
  name        = "test-tf"
  visibility = "public"
}

data "github_app" "app" {
  slug = "test-tf-branch-protection"
}

resource "github_branch_protection" "example" {
  repository_id = github_repository.test.node_id

  pattern          = "main"

  required_pull_request_reviews {
    required_approving_review_count = 1
    pull_request_bypassers = [data.github_app.app.node_id]
  }
}
```

The resulting config:

image

### CODE REVIEW

**Comment by strideynet** [comment]
I cannot add labels so I am unable to complete your pull request checklist.

**Comment by strideynet** [comment]
Hah, so it turns out this doesn't fix what I was trying to fix. 

However, it does fix the diffing to prevent it trying to re-apply the addition of an app to the `pull_request_bypasser`.

**Comment by Nexus2k** [comment]
Any update on this? We're currently also running in the issue of not being able to add Github Apps in pull_request_bypassers list.

**Comment by audunsolemdal** [comment]
> Hah, so it turns out this doesn't fix what I was trying to fix.
> 
> However, it does fix the diffing to prevent it trying to re-apply the addition of an app to the `pull_request_bypasser`.

This is very much appreciated for my part. Our tfplan is cluttered with false positives for re-applying apps that are already added as PR-bypassers

**Comment by strideynet** [comment]
> Any update on this? We're currently also running in the issue of not being able to add Github Apps in pull_request_bypassers list.

How are you trying to do this ? Are you using the app data source and then using the node id attribute of that ?

**Comment by audunsolemdal** [comment]
> > Any update on this? We're currently also running in the issue of not being able to add Github Apps in pull_request_bypassers list.
> 
> How are you trying to do this ? Are you using the app data source and then using the node id attribute of that ?

I tried getting this to work recently, but had some issues.

I get the node_id by the following method: https://github.com/integrations/terraform-provider-github/issues/1248#issuecomment-1239350036

a bit time consuming for one-time jobs, but it works.

**Comment by kfcampbell** [comment]
@strideynet I'm sorry, I saw this after merging #1453 with the same changes! I probably should've merged yours as you created your PR first.

**Comment by kfcampbell** [comment]
I'll create a new release with these changes shortly so you can at least take advantage of them.

**Pull request closed without merging**
