### PR TITLE
Add fork attribute to `github_repository` data

### PR DESCRIPTION
**Pull request by davidcorrigan714**
## Behavior

* Adds the `fork` attribute to the `github_repository` data.

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

### Pull request type

- Feature/model/API additions: `Type: Feature`

### CODE REVIEW

**Comment by davidcorrigan714** [comment]
Don't think I can add the label myself to the PR.

**Comment by kfcampbell** [comment]
Would you mind adding relevant test cases to the existing tests in github/data_source_github_repository_test.go?

**Comment by davidcorrigan714** [comment]
Ooops, saw those and totally forgot to add it in.

**Comment by davidcorrigan714** [comment]
Added a test. I don't see a way to create a fork through Terraform but at least it tests that it's readable. Though the property is read in all the tests so it'd fail elsewhere too if it was really an issue.

**Review by kfcampbell — APPROVED** [review]
Thank you for contributing!

**Pull request merged**
