### PR TITLE
Add release assets

### PR DESCRIPTION
**Pull request by shabbyrobe**
Add support for `assets` portion of Github [releases](https://docs.github.com/en/rest/releases/releases#get-a-release) to the output of the github release data source:

```
{
  // ...
  "assets": [
    {
      "url": "https://api.github.com/repos/octocat/Hello-World/releases/assets/1",
      "browser_download_url": "https://github.com/octocat/Hello-World/releases/download/v1.0.0/example.zip",
      "id": 1,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDE=",
      // ...
    }
  ]
}
```

Please let me know how I should test this; to run the tests it seems I needed to create a release and then pass the `GITHUB_TEMPLATE_REPOSITORY_RELEASE_ID=...` env var. I can configure a test that anticipates that the release referenced by that env var must have at least one asset attached to it. I presume I'd document that requirement in `CONTRIBUTING.md`?

### CODE REVIEW

**Comment by crqra** [comment]
Hey 👋🏽 any news about this?

**Comment by bogdangi** [comment]
It would be nice to have this feature!

**Comment by kfcampbell** [comment]
@shabbyrobe Sorry for the delay! It looks like the build failure is related to a website linting error that can easily be fixed. I'd be happy to get this in once it is!

As far as testing, I'm not sure. This is a great question and something I'm thinking about as well for #1120. Balancing the need for integration testing with the hassle of keeping several organizations and credentials current across several flavors of GitHub is obnoxious.

My immediate, tentative vote would be to postpone integration testing this functionality until we have working integration tests in CI.

**Comment by shabbyrobe** [comment]
Thanks for the update @kfcampbell, just fixed the typo, can you please re-approve the workflow?

**Pull request merged**
