### PR TITLE
Add a data source for refs.

### PR DESCRIPTION
**Pull request by youcandanch**
### Description
We're currently lacking a way to retrieve some basic information on a given ref within the Terraform provider. A crisp use case for this might be "I have a release that's based off of a tag, and I'd like to be able to retrieve the SHA1 for the HEAD commit in order to use elsewhere." This PR introduces a `github_ref` data source, which pretty shamelessly steals from the existing `github_branch` data source. I considered lifting out some of the code into a shared function, but the API calls are lightweight enough where I don't think there's that much harm from a few lines of duplication. 

Tests are currently passing and documentation has been added to the markdown.

### CODE REVIEW

**Comment by youcandanch** [comment]
@kfcampbell this one's probably simpler to land then #1066, which I haven't had as much time to work on. Any chance you could kick the workflows for this as well? Thanks so much!

**Comment by kfcampbell** [comment]
@youcandanch Done! 

Do you also mind linking to the sweet new docs page you just created in the [.erb file](https://github.com/integrations/terraform-provider-github/blob/main/website/github.erb#L14)? Thanks!

**Comment by youcandanch** [comment]
@kfcampbell all set!

**Review by kfcampbell — APPROVED** [review]
Thank you for the contribution! I'll shoot to get this released at the end of this week.

**Comment by youcandanch** [comment]
@kfcampbell looks like an older commit of mine made it up here, which means there's some errors in the ref code. I'm gonna fix it, but I'm also gonna glance and see why tests were able to pass, as I don't think there's a way they _should_ be passing right now. Issue opened here: https://github.com/integrations/terraform-provider-github/issues/1108

**Pull request merged**
