### PR TITLE
feat(github_release): adding github_release resource and tests

### LINKED ISSUE #692: [Feature Request] Provide 'github_Releases' resource
I would find it vary useful if there was a resource [`github_release`](https://docs.github.com/en/rest/reference/repos#create-a-release) that could be used to manage the creation an updating of a github release. There is already the accompanying [data source](https://github.com/integrations/terraform-provider-github/pull/356)

this could then spawn the creation of [`github_release_asset`](https://docs.github.com/en/rest/reference/repos#upload-a-release-asset)

### PR DESCRIPTION
**Pull request by trentmillar**
closes #692 

I haven't done anything with the website docs yet but can if this is approved.

### CODE REVIEW

**Comment by trentmillar** [comment]
> closes #692
> 
> I haven't done anything with the website docs yet but can if this is approved.

~~I haven't done anything with the website docs yet but can if this is approved.~~

Just added the docs for the resource.

**Comment by djalanmwp** [comment]
Happy to test this out, but @trentmillar are you available to pull in the changes to your fork beforehand? 

I'm not familiar with the velocity of merges or status on this repo, but looks like PR needs a refresh.

**Comment by kfcampbell** [comment]
This is definitely still valid and useful. @trentmillar please feel free to fix the merge and I will validate the integration tests. If you don't get to it, I can sometime soon! Thank you for contributing.

**Review by kfcampbell — APPROVED** [review]
Confirming integration tests are passing for me locally. Thanks for opening up the PR!

**Pull request merged**
