### PR TITLE
feat(team_membership): allow id lookup from slug

### LINKED ISSUE #1501: [FEAT]: github_team_membership doesn't allow slug instead of team id
### Describe the need

If you try to pass in the slug version of a team to team id instead of the actual numerical id you run into this issue:

`│ Error: Unexpected ID format ("developers"), expected numerical ID. strconv.ParseInt: parsing "developers": invalid syntax
│ 
│   with github_team_membership.ghe_team_membership["developers.member.blah"],
│   on team_membership.tf line 14, in resource "github_team_membership" "ghe_team_membership":
│   14: resource "github_team_membership" "ghe_team_membership" {
│ `

This happens for [github_team_membership](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/team_membership) but not for [github_team_repository](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/team_repository). The documentation does make it clear, but it would be a great enhancement if we could instead be able to do it as well for github_team_membership.

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

```shell
Error: Unexpected ID format ("developers"), expected numerical ID. strconv.ParseInt: parsing "developers": invalid syntax
│ 
│   with github_team_membership.ghe_team_membership["developers.member.blah"],
│   on team_membership.tf line 14, in resource "github_team_membership" "ghe_team_membership":
│   14: resource "github_team_membership" "ghe_team_membership" {
│
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jhoenzsch**
Resolves #1501

----

### Before the change?

* github_team_membership allows passing in the team slug as a team id.

### After the change?

* github_team_membership allows passing in the team slug as a team id.
----

### Pull request checklist
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [X] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Review by kfcampbell — APPROVED** [review]

**Comment by csainty** [comment]
This turned a `parseInt()` in to an api call - https://github.com/integrations/terraform-provider-github/blob/main/github/util.go#L163
We don't use this resource any longer, so I don't have a ready test setup, but unless there is caching down the stack this would have been an explosion of requests (X users * Y repos).

**Comment by dennislapchenko** [comment]
@jhoenzsch Hey. You think same can be done for `github_team_members` resource?

**Comment by kfcampbell** [comment]
@csainty are you experiencing this effect yourself yet?

**Comment by csainty** [comment]
@kfcampbell No we don't use it, I was just browsing the release notes and reading diffs.

**Pull request merged**
