### PR TITLE
Use correct base url for `gh auth token --hostname`

### PR DESCRIPTION
**Pull request by nfx**
This PR is a follow-up to https://github.com/integrations/terraform-provider-github/pull/1854

### Before the change?

GitHub CLI uses different base URLs in `~/.config/gh/hosts.yml`, so when we're using the standard base path of this provider, it doesn't align with how `gh` CLI stores the credentials - I think some of the recent CLI changes made this effect (or `gh` was not updated for a while on my machine). The following doesn't work:

```
$ gh auth token --hostname api.github.com
> no oauth token
```
... but the following does work correctly

```
$ gh auth token --hostname github.com
> gh..<valid token>
```

attempted a workaround with

```
provider "github" {
  owner = "..."
  base_url = "github.com"
}
```

But it didn't work as expected.

### After the change?

provider conf works:

```
provider "github" {
  owner = "..."
}
```

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Comment by nfx** [comment]
@nickfloyd @kfcampbell please review :)

**Comment by nickfloyd** [comment]
Hey @nfx This was addressed [here](https://github.com/integrations/terraform-provider-github/blob/main/github/provider.go#L394C54-L394C54) in this [PR](https://github.com/integrations/terraform-provider-github/pull/1906).  

I'm going to close this now that the other has been  merged in. Thank you for working to make our community better!

**Comment by nickfloyd** [comment]
We're still working through the solution over [here](https://github.com/integrations/terraform-provider-github/issues/1905) - join the conversation if you have time!

**Comment by nfx** [comment]
Let's see..,

**Comment by nfx** [comment]
@nickfloyd are we going to merge this with comments or close it? :) recent version picks up the token nicely, btw

**Review by nickfloyd — APPROVED** [review]
Thanks for the additional effort here @nfx.  I'm going to get this merged in and released but I think I am going to have another look at the logic here and see if I can simplify it and/or determine if there are any more edge cases that we could've missed.  

Thanks again for everything here!

**Pull request merged**
