### PR TITLE
feat: Add a data source for branch protection rules.

### LINKED ISSUE #1206: [Feature Request] Add a data source for retrieving branch protection rules for repository.
It'd be brilliant if it was possible to retrieve a list of all the branch protection rules for a repository through a GitHub provider data source.

I'd expect such a data source to return:
```json
{
  "id": "",
  "rules": [
    {
      "pattern": "",
    }, ...
  ]
}
```

All the arguments required to perform such an action are: `repository`.

GitHub GraphQL API allows such an operation through https://docs.github.com/en/graphql/reference/objects#repository

### References

- https://github.com/integrations/terraform-provider-github/pull/1207

### PR DESCRIPTION
**Pull request by galargh**
Resolves #1206

###### Description

This PR adds a data source for branch protection rules. Given a repository name, it returns a list of branch protection rules associated with that repository.

I added a [markdown entry](https://github.com/galargh/terraform-provider-github/blob/e5ac6bdf4812e01c64bb9a19957dd248a95ba714/website/docs/d/branch_protection_rules.html.markdown) which describes how to configure the new data source.

###### Testing

- [x] `TF_ACC=1  go test -v   ./... -run ^ TestAccGithubBranchProtectionRulesDataSource`

### CODE REVIEW

**Comment by kfcampbell** [comment]
@galargh sorry I missed this; is this still a feature you're interested in getting shipped?

**Comment by othmane399** [comment]
Hello @kfcampbell, this PR is stale for a moment ? can you look at it please ? I can eventually fork and fix what needed to make it merge :)

**Comment by galargh** [comment]
> @galargh sorry I missed this; is this still a feature you're interested in getting shipped?

Hey! Thanks for the reply :) Yes, I still think it'd be nice to have. It's not a strict requirement for my use cases anymore though.

**Review by kfcampbell — APPROVED** [review]
Confirming that the added integration tests are passing. Thank you for contributing!

**Comment by othmane399** [comment]
Hey @kfcampbell sorry for disturbing can we merge this PR then ? 🙏

**Pull request merged**
