### PR TITLE
Add Dependabot secrets support (Fixes #1006)

### LINKED ISSUE #1006: Add support for Dependabot secrets
### Terraform Version

0.14.5

### Affected Resource(s)

None that already exists.

### Expected Behavior

I can create secrets for Dependabot.

### Actual Behavior

I can't create secrets for Dependabot.

### Steps to Reproduce

1. Try to create a secret for Dependabot.

### Important Factoids

These secrets can be set at the organisation- or project-level. I'd need both ideally.

### References

https://github.blog/changelog/2021-11-30-github-actions-workflows-triggered-by-dependabot-receive-dependabot-secrets/

### PR DESCRIPTION
**Pull request by liath**
This PR allows us to manage Dependabot's secrets. It depends on the go-github version bump here: https://github.com/integrations/terraform-provider-github/pull/1035

I considered just adding a `dependabot` flag to the existing resources but a dev who worked on the underlying API warned that these methods could diverge from the normal Actions secrets API I felt it was prudent to keep them split. It made implementing very straightforward too, just copy and sed replaced some things.

Leaving as draft for now because I haven't tested it.

Fixes #1006

### CODE REVIEW

**Comment by liath** [comment]
Link the discussion I was talking about in the middle there: https://github.com/google/go-github/pull/2248#issuecomment-1011011001

**Comment by liath** [comment]
Forgot to rebase to pick up #1035, also there was some minor lint in `github/data_source_github_organization_teams_test.go`

**Comment by kfcampbell** [comment]
I'm 👍 on the general changes. When I try to run the tests, I do so with the following:

```
export GITHUB_TOKEN={redacted}
export GITHUB_OWNER=kfcampbell-terraform-provider # my test org
export TF_LOG=debug
export TF_ACC=1
go test -v -timeout 300s -run TestAccGithubDependabot github.com/terraform-providers/terraform-provider-github/github
```

and I'm seeing the following test failures:

```
=== RUN   TestAccGithubDependabotSecret/deletes_secrets_without_error/with_an_organization_account
    provider_utils.go:62: GITHUB_TOKEN and GITHUB_ORGANIZATION environment variables should be set
    provider_utils.go:66: Skipping TestAccGithubDependabotSecret/deletes_secrets_without_error/with_an_organization_account which requires organization mode
--- FAIL: TestAccGithubDependabotSecret (18.13s)
    --- PASS: TestAccGithubDependabotSecret/reads_a_repository_public_key_without_error (7.69s)
        --- SKIP: TestAccGithubDependabotSecret/reads_a_repository_public_key_without_error/with_an_anonymous_account (0.00s)
        --- PASS: TestAccGithubDependabotSecret/reads_a_repository_public_key_without_error/with_an_individual_account (7.69s)
        --- SKIP: TestAccGithubDependabotSecret/reads_a_repository_public_key_without_error/with_an_organization_account (0.00s)
    --- FAIL: TestAccGithubDependabotSecret/creates_and_updates_secrets_without_error (9.93s)
        --- SKIP: TestAccGithubDependabotSecret/creates_and_updates_secrets_without_error/with_an_anonymous_account (0.00s)
        --- FAIL: TestAccGithubDependabotSecret/creates_and_updates_secrets_without_error/with_an_individual_account (9.93s)
        --- SKIP: TestAccGithubDependabotSecret/creates_and_updates_secrets_without_error/with_an_organization_account (0.00s)
    --- PASS: TestAccGithubDependabotSecret/deletes_secrets_without_error (0.51s)
        --- SKIP: TestAccGithubDependabotSecret/deletes_secrets_without_error/with_an_anonymous_account (0.00s)
        --- PASS: TestAccGithubDependabotSecret/deletes_secrets_without_error/with_an_individual_account (0.51s)
        --- SKIP: TestAccGithubDependabotSecret/deletes_secrets_without_error/with_an_organization_account (0.00s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-github/github	26.005s
FAIL
```

@liath Can you reproduce this? What happens when you do?

**Comment by liath** [comment]
The actions secrets also fail in the same way*

**Comment by liath** [comment]
Well, I tried to clear that merge conflict. Idk why it's still complaining.

**Comment by ilmax** [comment]
Is there anything we (community) can do to either help with this PR? I'm really looking forward to have dependabot secret available

**Comment by liath** [comment]
It seems like Hashicorp runs on upvotes lol, get your team to bomb the :+1: :)

**Comment by kfcampbell** [comment]
@liath I agree that this is important work. Unfortunately this project is not supported officially by GitHub and I've been doing it in my spare time. I've been trying to change that (and in the meantime have been granted a few hours a week to work on it), so velocity on the project should pick up a little bit. I can't promise any specific dates, but after #1094 goes in, this and #987 are high on my radar.

**Comment by liath** [comment]
I assumed Hashicorp maintained it lol, no rush! I appreciate your effort :)

**Comment by thor** [comment]
Noting that this fixes #1006; would you add that to the description? More importantly, do you want to pull from upstream and rebase on `main`, @liath, or is there anything I could help with to solve the merge conflicts? 🙇

**Comment by ohookins** [comment]
@kfcampbell any chance this will actually make the next release? I could really use this!

**Review by kfcampbell — APPROVED** [review]
Sorry about the delay, folks. Thank you @liath for submitting this PR and the updates!

**Pull request merged**
