### PR TITLE
Harden resource github_actions_runner_group

### LINKED ISSUE #969: Runner Group Selected Repositories IDs in constant drift
When the number of selected repositories is higher than 30 - the resource is in constant drift.

### Affected Resource(s)
github_actions_runner_group

### Terraform Configuration Files
```hcl
resource "github_actions_runner_group" "project" {
  name                    = var.group_name
  visibility              = "selected"
  selected_repository_ids = values(data.github_repository.this)[*].repo_id
}
```

### Expected Behavior
Once applied, there will be no drift.

### Actual Behavior
Terraform shows drift for `length(selected_repositories) - 30` repos

### Steps to Reproduce
1. `terraform apply`
2.`terraform apply`

### PR DESCRIPTION
**Pull request by Vladyslav-Miletskyi**
Resolves #969 #967

### CODE REVIEW

**Comment by Vladyslav-Miletskyi** [comment]
@jcudit Review me pls

**Comment by toast-gear** [comment]
Running into this and it's causing lots of issue for us :(

**Comment by g-chouzadjian** [comment]
Yeah same here, could use this fix ASAP

**Comment by patrickmarabeas** [comment]
Any chance for a `v4.18.1` release @jcudit ?

**Comment by petracvv** [comment]
Thanks for merging the fix! Do you know how long a new release takes to appear on the terraform registry?

**Pull request merged**
