### PR TITLE
Add `branches` attribute to `github_repository`

### PR DESCRIPTION
**Pull request by mikeroll**
Addresses #748. 

Adding `branches` to both the resource and the data source.

### CODE REVIEW

**Review by jcudit — COMMENTED** [review]
Can we get a test added or modified to incorporate the new field?  Otherwise looks 👌🏾 with the docs update and implementation!

**Comment by mikeroll** [comment]
@jcudit I've only seen tests around for more advanced stuff like resource modification and nontrivial logic, so I figured we don't normally test simple things like this. I'll have another look though!

**Review by jcudit — APPROVED** [review]
Looks good after verifying locally:

```sh
STATE:

data.github_repository.test:
  ID = tf-acc-hgsf1
  provider = provider.github
  allow_merge_commit = true
  allow_rebase_merge = true
  allow_squash_merge = true
  archived = false
  branches.# = 1
  branches.0.name = main
  branches.0.protected = false
```

**Comment by mikeroll** [comment]
Thank you for finalising this, I got distracted by other things unfortunately.

**Pull request merged**
