### PR TITLE
fix: Add build_type to datasource github_repository's pages (closes #1709)

### LINKED ISSUE #1709: [BUG] datasource github_repository fails when actions enabled
PR #1663 added the "build_type" attribute to the github_repository resource. Since the corresponding data source uses the same code to parse the pages endpoint data, any use of the github_repository datasource would lead to an error, since the attribute does not exist there.

main.tf:
```terraform
data "github_repository" "jekyll" {
  full_name = "jekyll/jekyll"
}
```

run:
```bash
$ terraform plan
data.github_repository.jekyll: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: error setting pages: Invalid address to set: []string{"pages", "0", "build_type"}
│ 
│   with data.github_repository.jekyll,
│   on main.tf line 1, in data "github_repository" "jekyll":
│    1: data "github_repository" "jekyll" {
│ 
╵
```

### PR DESCRIPTION
**Pull request by soult**
PR #1663 added the "build_type" attribute to the github_repository resource. Since the corresponding data source uses the same code to parse the pages endpoint data, any use of the github_repository datasource would lead to an error, since the attribute did not exist there:

> Error: error setting pages: Invalid address to set: []string{"pages", "0", "build_type"}

This commit adds the missing attribute. The existing acceptance tests already cover it, failed for me when running without this commit, and passed after.

Resolves #1709

----

### Before the change?
Provider would error for github_repository data sources, when the repository had actions enabled (both legacy and workflow build_types).

### After the change?
Provider exposes new `build_type` attribute inside `pages` map for `github_repository` datasource.

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

### CODE REVIEW

**Review by dcfranca — APPROVED** [review]

**Comment by bpaquet** [comment]
@kfcampbell I confirm this PR fix an issue in the 0.5.26 and is blocking us :) Integration tests (`TestAccGithubRepositoryDataSource` are green with this.) Thx :)

**Comment by arcnmx** [comment]
:+1: can confirm this fixes the issue - this has been preventing an apply from working at all here.

**Review by kfcampbell — APPROVED** [review]
@soult thank you! I'll get this merged and released shortly.

**Comment by soult** [comment]
Thanks @kfcampbell for getting this merged :bow:

**Pull request merged**
