### PR TITLE
use GetRoleName() instead of permission mapping func

### PR DESCRIPTION
**Pull request by joshua-hancox**
Requires go-github version bump: https://github.com/integrations/terraform-provider-github/pull/1205

fixes: https://github.com/integrations/terraform-provider-github/issues/1183

### CODE REVIEW

**Review by kfcampbell — APPROVED** [review]
Thank you for doing this! Apologies for the delay.

**Comment by csainty** [comment]
This breaks the resource for non-custom roles as they naming is different. `read` vs `pull`, `write` vs `push` etc.

**Comment by Tenzer** [comment]
I'm seeing the same as @csainty. Confusingly, around half of the repositories we manage seem to use "push" and the other half "write". It could look like the oldest repositories we have wants to use "push", so I'm guessing it might have something to do with when the repository is created.

Not having it mapped to the same name makes it difficult to use `for_each` to assign a list of repositories to a group with the correct permissions.

**Comment by schans** [comment]
Same here. This is a breaking change for use. If we keep it as is some 300 repos will be changed on every run, if we change push to write, some 450 repos will be changed every run. 

We should revert or create some option to have aliases or something.

**Comment by schans** [comment]
Created a new ticket in https://github.com/integrations/terraform-provider-github/issues/1222 as comments here might get unnoticed.

**Pull request merged**
