### PR TITLE
make `github_ref` respect `owner`

### LINKED ISSUE #1650: [MAINT]: Make `github_ref` respect `owner` (vs taking it from the PAT)
### Describe the need

Currently, the `github_ref` data source does not take an `owner` input and defaults to the one that can be derived from the PAT.

When using the data source with a personal access token (for my user `ksatirli`), this results in an empty response for a `github_ref` for `hashicorp/setup-terraform`:

```hcl
data "github_ref" "terraform" {
  ref        = "tags/v2.0.3"
  owner      = "hashicorp"
  repository = "setup-terraform"
}
```

Output:

```
  "etag" = tostring(null)
  "id" = tostring(null)
  "ref" = tostring(null)
  "repository" = tostring(null)
  "sha" = tostring(null)
```

Comparatively: when I poll a `repository` that belongs to the same `owner` as the PAT, the data source works as expected.

Change request: The `github_ref` data source should support an `owner` attribute that is used to query the GH API.

### SDK Version

5.22.0 and earlier

### API Version

n/a

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ksatirli**
Hello maintainers 👋🏼 

Resolves #1650

----

### Before the change?

* The `github_ref` data source is **not** able to provide data on repositories that are not of the same owner as the PAT / token

```
  "etag" = tostring(null)
  "id" = tostring(null)
  "ref" = tostring(null)
  "repository" = tostring(null)
  "sha" = tostring(null)
``` 

### After the change?

* The `github_ref` data source **is** able to provide data on repositories that are not of the same owner as the PAT / token

```
  "etag" = "W/\"a1946ae73434cb3bcf8720087f56b426943582a4debb54785c4d43d631b581dc\""
  "id" = "setup-terraform:tags/v2.0.3"
  "owner" = "hashicorp"
  "ref" = "tags/v2.0.3"
  "repository" = "setup-terraform"
  "sha" = "633666f66e0061ca3b725c73b2ec20cd13a8fdd1"
```

### Other information

* 

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

The `github_ref` data source now requires an `owner` attribute. I marked it as `required` in the code, which brings this data source in line with other data sources.

Not providing an `owner` would result in Terraform informing the user of a missing attribute (`owner`), which could break a deployment.

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [X] Yes (Please add the `Type: Breaking change` label)
- [ ] No

If `Yes`, what's the impact:  

* When using the `github_ref` data source, an `owner` attribute must now be provided.

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`

----

### CODE REVIEW

**Comment by kfcampbell** [comment]
As we discussed on Slack, let's try making the owner optional so that we can release this as a non-breaking change. Would you like to do that? Should I push commits to this PR?

**Comment by kfcampbell** [comment]
Psst...hi! I don't want to step on your toes here but it would be great to get this in soon. Want me to make the owner optional?

**Comment by ksatirli** [comment]
I'd love to get this in ASAP, too!

This week and early of next are fully booked, so if you can get to it earlier, please do!

**Review by kfcampbell — APPROVED** [review]
I've tested this locally and it works! This is a change we probably need to make across _many_ resources. I've opened #1655 to track this work. 

Thank you for contributing!

**Pull request merged**
