### PR TITLE
feat: allow_update_branch argument

### LINKED ISSUE #1072: [Pull Requests] less `Always suggest updating pull request branches` avariable for the repository.
Hi,
I'd like to request the resource for github-repository less  `Always suggest updating pull request branches`.
https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-suggestions-to-update-pull-request-branches

### Terraform Version
The latest version
### Affected Resource(s)
- resource_github_repository

### PR DESCRIPTION
**Pull request by strantalis**
This argument allows toggling `Always suggest updating pull request branch` in the repository settings. Closes #1072 but is dependent by #1138 as this needs `v44` of `go-github`.

### CODE REVIEW

**Review by bateller — APPROVED** [review]

**Comment by rene-bos** [comment]
The dependent PR (https://github.com/integrations/terraform-provider-github/pull/1138) has been merged, so I think nothing blocks this PR from being finalized and merged. @strantalis do you have time to fix the conflicts?

**Comment by strantalis** [comment]
@rene-bos Yeah I can get those fixed this week.

**Comment by EvyBongers** [comment]
When could this PR be merged?

**Comment by EvyBongers** [comment]
@bateller Can you approve the workflow? I'm hoping to see this PR merged soon, since it's blocking some work I have planned

**Comment by gesellix** [comment]
This would be great to be included in the next release :)

**Comment by github-matthieu-wipliez** [comment]
Hi, I just stumbled upon this PR, great job 🎉 ! Looking forward to a merge 😁

**Comment by kfcampbell** [comment]
I've updated the PR and fixed the merge conflict. I love this feature and we have it enabled on this repo! This will be released shortly.

**Pull request merged**
