### PR TITLE
chore(organization_webhook): fix insecure_ssl

### LINKED ISSUE #2142: [BUG]: github_organization_webhook resource creation fake-failure
### Expected Behavior

When creating this resource:

```
resource "github_organization_webhook" "generic_webhook" {
  configuration {
    url          = "<hidden>"
    content_type = "json"
    insecure_ssl = false
    secret = var.gh_api_token
  }
  active = var.active_regions_api["us-west-2"]
  events = ["push", "pull_request" ]
}
```

This should create a new webhook, as described in the documentation: https://registry.terraform.io/providers/integrations/github/latest/docs/resources/organization_webhook#configuration 

### Actual Behavior

TF throws an error: 

```
╷
│ Error: configuration.0.insecure_ssl: '' expected type 'bool', got unconvertible type 'string', value: '0'
│ 
│   with github_organization_webhook.generic_webhook,
│   on webhooks.tf line 1, in resource "github_organization_webhook" "generic_webhook":
│    1: resource "github_organization_webhook" "generic_webhook" {
│ 
╵
```

The problem is that we web hook actually gets created:
Screenshot 2024-02-12 at 11 03 20

So the next execution will delete and recreate the resource. 

Additionally, the same resource type that was created with v5.x of the provider works just fine. The bug affects only the creation of a new webhook. 

### Terraform Version

Terraform 1.7.2 on linux_amd64
Affected versions: v6.0.0.0-rc2 (I have tested the creation of a new webhook only on this one)

### Affected Resource(s)

github_organization_webhook

### Terraform Configuration Files

_No response_

### Steps to Reproduce

_No response_

### Debug Output

_No response_

### Panic Output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by EttoreFoti**
Resolves #2142

----

### Before the change?

* The Provider was missing the conversion step causing type mismatch for go.

### After the change?

* The Provider does the correct parsing of the input.

### Pull request checklist
- [-] Tests for the changes have been added (for bug fixes / features)
- [-] Docs have been reviewed and added / updated if needed (for bug fixes / features)
Both are not needed since it's just a fix over already existing resource.

### Does this introduce a breaking change?
- [ ] Yes
- [X] No

----

### CODE REVIEW

**Comment by kfcampbell** [comment]
@EttoreFoti can you describe (and perhaps include output from) the testing process you used here, since integration tests aren't added?

**Comment by EttoreFoti** [comment]
> @EttoreFoti can you describe (and perhaps include output from) the testing process you used here, since integration tests aren't added?

Just run the current AcceptanceTest that was previously failing, I can copy paste output if needed.

**Comment by gm-hyp-2** [comment]
@kfcampbell hello! Can you please review and release if it is all ok? thanks!

**Comment by EttoreFoti** [comment]
@kfcampbell any update on this?

**Comment by kfcampbell** [comment]
The test used to panic for me and now it's failing. I'm seeing the following output: 

```
--- FAIL: TestAccGithubOrganizationWebhook (17.29s)
    --- FAIL: TestAccGithubOrganizationWebhook/creates_and_updates_webhooks_without_error (7.06s)
        --- SKIP: TestAccGithubOrganizationWebhook/creates_and_updates_webhooks_without_error/with_an_anonymous_account (0.00s)
        --- SKIP: TestAccGithubOrganizationWebhook/creates_and_updates_webhooks_without_error/with_an_individual_account (0.00s)
        --- FAIL: TestAccGithubOrganizationWebhook/creates_and_updates_webhooks_without_error/with_an_organization_account (7.06s)
    --- PASS: TestAccGithubOrganizationWebhook/imports_webhooks_without_error (10.23s)
        --- SKIP: TestAccGithubOrganizationWebhook/imports_webhooks_without_error/with_an_anonymous_account (0.00s)
        --- SKIP: TestAccGithubOrganizationWebhook/imports_webhooks_without_error/with_an_individual_account (0.00s)
        --- PASS: TestAccGithubOrganizationWebhook/imports_webhooks_without_error/with_an_organization_account (10.23s)
FAIL
```

The specific error is:

```
    resource_github_organization_webhook_test.go:53: Step 1/2 error: Error running apply: exit status 1
        
        Error: POST https://api.github.com/orgs/kfcampbell-terraform-provider/hooks: 422 Validation Failed [{Resource:Hook Field: Code:custom Message:Hook already exists on this organization}]
        
          with github_organization_webhook.test,
          on terraform_plugin_test.tf line 9, in resource "github_organization_webhook" "test":
           9: 			resource "github_organization_webhook" "test" {
```

but that's possibly related to the org I'm using for testing and/or a dirty integration test setup. Does it pass cleanly now for you?

**Review by kfcampbell — APPROVED** [review]
Regardless of whether the issue is one of test setup on my side, this is an improvement over the current test setup, so I'm comfortable taking the change as-is.

**Pull request merged**
