### PR TITLE
Update data source for repository file: prevent tf panic on non-existent file and make the branch default consistent with GitHub API

### LINKED ISSUE #1131: The repository_file data source throws an error when trying to access a non-existent file
### Affected Resource(s)
Please list the resources as a list, for example:
- `data.github_repository_file`

### Expected Behavior
The `repository_file` data source allows checking if a specific file exists in a repository. The same way that `branch`data source, for example, does (see: https://github.com/integrations/terraform-provider-github/blob/main/github/data_source_github_branch.go#L52).

### Actual Behavior
The `repository_file` data source throws an error when trying to get a file which does not exist (see: https://github.com/integrations/terraform-provider-github/blob/main/github/data_source_github_repository_file.go#L82).

### References
- https://github.com/integrations/terraform-provider-github/pull/1129

### LINKED ISSUE #1132: The default value of repository_file.branch parameter is not consistent with GitHub API
### Affected Resource(s)
Please list the resources as a list, for example:
- `github_repository_file`
- `data.github_repository_file`

### Expected Behavior
The `branch` parameter of `repository_file` resource/data source is consistent with the GitHub API and defaults to the name of the default branch of the repository (see: https://docs.github.com/en/rest/repos/contents#create-or-update-file-contents--parameters). 

### Actual Behavior
The `branch` parameter of `repository_file` resource/data source defaults to `main`. (see: https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_file#argument-reference + https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/repository_file#argument-reference)

### References
- https://github.com/integrations/terraform-provider-github/pull/1128
- https://github.com/integrations/terraform-provider-github/pull/1129

### PR DESCRIPTION
**Pull request by galargh**
Resolves #1132
Resolves #1131

###### Description

This PR updates the data source for repository files.

It prevents terraform from panicking when trying to retrieve info about a non-existent file. With this change, in such a case, an empty data source will get returned - similarly to how `ref` data source behaves.

It also changes the default value for `branch` argument from `main` to the name of the default branch of the requested repository. The new behaviour is how GitHub API itself behaves.

I also added a new attribute `ref` which, after apply, holds the name of the branch the file is associated with. In practice, if a branch was explicitly provided, then `ref` = `branch`. Otherwise, `ref` = the name of the default branch of the requested repository.

Finally, it simplified the commit info retrieval. It was possible because I noticed that `commit_sha` is never set on the data source - I suspect it was copied over from the resource and just left in place.

I updated the [markdown entry](https://github.com/galargh/terraform-provider-github/blob/bdb51c391870ce64335eba06a9492ce24dfdac5f/website/docs/d/repository_file.html.markdown) which describes how to configure the resource.

###### Testing
- [x] `TF_ACC=1  go test -v ./... -run ^TestAccGithubRepositoryFileDataSource`

### CODE REVIEW

**Comment by douernesto** [comment]
This would solve a lot of issues!

**Comment by kfcampbell** [comment]
@galargh do you have any interest in resolving this merge conflicts? I can do a pass at it if you'd prefer as well.

**Comment by galargh** [comment]
> @galargh do you have any interest in resolving this merge conflicts? I can do a pass at it if you'd prefer as well.

Sure, no problem. All conflicts should be resolved now.

**Comment by kfcampbell** [comment]
Hmm, tests for `TestDataSourceGithubRepositoryFileRead` are failing for me. Here is some example test output: 

```
    data_source_github_repository_file_test.go:373: 
        	Error Trace:	/home/kfcampbell/github/dev/terraform-provider-github/github/data_source_github_repository_file_test.go:373
        	Error:      	Not equal: 
        	            	expected: "here-goes-content-of-our-glorious-config.json"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-here-goes-content-of-our-glorious-config.json
        	            	+
        	Test:       	TestDataSourceGithubRepositoryFileRead/using_user_as_owner_if_just_name_is_passed
    data_source_github_repository_file_test.go:374: 
        	Error Trace:	/home/kfcampbell/github/dev/terraform-provider-github/github/data_source_github_repository_file_test.go:374
        	Error:      	Not equal: 
        	            	expected: "test-repo/test-file.json"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-test-repo/test-file.json
        	            	+
        	Test:       	TestDataSourceGithubRepositoryFileRead/using_user_as_owner_if_just_name_is_passed
```

Can you reproduce this?

**Comment by galargh** [comment]
I've just realised I was only running `TestAccGithubRepositoryFileDataSource` before 🤦 

I now fixed `[TestDataSourceGithubRepositoryFileRead](https://github.com/integrations/terraform-provider-github/pull/1129/commits/1a8161ff9d5e3529e5b1c6cafac8a370adb59d98)` too. I needed to update GitHub client mock responses which totally makes sense since the ds is making slightly different requests now.

I also ran `go fmt` on modified files.

**Review by kfcampbell — APPROVED** [review]
@galargh thank you so much for contributing and following up! I'll get this merged and released shortly.

**Pull request merged**
