### PR TITLE
Allow GitHub app actors in all pull_request_bypassers and dismissal_restrictions branch protection settings

### LINKED ISSUE #1156: Adding the provider GitHub App to the branch protection exception list causes an error
GitHub recently added the ability to put GitHub Apps in the branch protection exception list so the GitHub App can bypass branch protection rules. This is useful if I want to drop GitHub Action workflow templates into repos in my organization without requiring a PR, or use the FluxCD provider to bootstrap flux manifests in repos.

https://github.blog/changelog/2022-05-17-consistently-allow-github-apps-as-exceptions-to-branch-protection-rules/

However, when I tested this new feature I noticed it caused an error when Terraform attempted to create the plan.

As soon as I removed the GitHub App from the branch protection rule exception list, the plan worked correctly again.

### Terraform Version

``` sh
# terraform -v
Terraform v1.1.8
on linux_amd64
```

### Affected Resource(s)
- github_branch_protection

### Terraform Configuration Files
```hcl
resource "github_branch_protection" "this" {
  for_each = { for branch in local.settings.protected_branches : branch.pattern => branch }

  repository_id                   = github_repository.this.node_id
  pattern                         = each.value.pattern
  enforce_admins                  = try(each.value.enforce_admins, true)
  allows_deletions                = try(each.value.allows_deletions, false)
  allows_force_pushes             = try(each.value.allows_force_pushes, false)
  required_linear_history         = try(each.value.required_linear_history, false)
  require_conversation_resolution = try(each.value.require_conversation_resolution, true)

  required_pull_request_reviews {
    dismiss_stale_reviews           = try(each.value.dismiss_stale_reviews, true)
    required_approving_review_count = try(each.value.required_approving_review_count, 1)
    require_code_owner_reviews      = try(each.value.require_code_owner_reviews, false)

    pull_request_bypassers = try(data.github_users.pull_request_bypassers[each.key].node_ids, [])
  }

  required_status_checks {
    strict   = try(each.value.strict, true)
    contexts = each.value.contexts
  }

}
```

### Expected Behavior

A plan should have been created.

### Actual Behavior

```
╷
│ Error: Something went wrong while executing your query. Please include `0681:9080:C14D4:D695D:62879F7D` when reporting this issue.
│ 
│   with module.repos["flux-system"].github_branch_protection.this["main"],
│   on ../modules/gh-repo/main.tf line 63, in resource "github_branch_protection" "this":
│   63: resource "github_branch_protection" "this" {
│ 
╵
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. Add the provider GitHub App to a branch protection exception list on a repo.
2. Attempt to plan that will trigger a `GET` on the branch protection rules (`github_branch_protection` resource)
3. `terraform plan`

### PR DESCRIPTION
**Pull request by vgrigoruk**
Added support for Github App IDs in `pull_request_bypassers` and `dismissal_restrictions` branch protection rules

Fixes #1156

### CODE REVIEW

**Comment by julien-michaud** [comment]
is it possible to resolve the conflicts and merge this PR please ? I really need it 

Thanks

**Comment by kfcampbell** [comment]
@vgrigoruk is this something you're still interested in?

**Comment by Nexus2k** [comment]
pingo pongo, we'd be interested in getting this fixed too.

**Comment by paymand** [comment]
@vgrigoruk See https://github.com/integrations/terraform-provider-github/issues/1156#issuecomment-1483762525
I think this PR can be closed now.

**Pull request closed without merging**
