### PR TITLE
feat: Add support for GitHub Actions OpenID Connect subject claim customization templates

### LINKED ISSUE #1458: [FEAT]: Add resources to customize OIDC subject claims
### Describe the need

I would like to be able to customize OICD subject claims for GitHub actions on a per-repo or per-organization basis.
This can be accomplished via the API, but it would be really great if we can do this in Terraform too.

Docs: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#customizing-the-subject-claims-for-an-organization-or-repository
API: https://docs.github.com/en/rest/actions/oidc#set-the-customization-template-for-an-oidc-subject-claim-for-a-repository

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by F21**
Resolves #1458

----

## Behavior
This adds support for OpenID Connect subject claim customization templates for GitHub Actions.
More information regarding this feature here: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect

~~Note: This requires features I recently committed to [google/go-github](https://github.com/google/go-github), which are currently unreleased, so it pins [google/go-github](https://github.com/google/go-github) to `e4ff2a27f7699954c87d81d723012c1c3f0de0f1`. The PR will be updated to pin a released version of `go-github` as soon as the maintainers tag a new release.~~

### Before the change?
It was not possible to manage OpenID Connect subject claim customization templates for GitHub Actions using Terraform.

### After the change?
This change adds 2 resources and 2 data sources for managing OpenID Connect subject claim customization templates on an organization and repository basis:
- `github_actions_organization_oidc_subject_claim_customization_template`
- `github_actions_repository_oidc_subject_claim_customization_template`
- `data.github_actions_organization_oidc_subject_claim_customization_template`
- `data.github_actions_repository_oidc_subject_claim_customization_template`

### Other information
None.

----

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Added the appropriate label for the given change

### Does this introduce a breaking change?
- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

### Pull request type

Please add the corresponding label for change this PR introduces:
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`

----

### CODE REVIEW

**Comment by nickfloyd** [comment]
@F21 Thank you for these contributions ❤️.  We'll wait to do the final review/merge until they drop a new version of go-GitHub and it gets updated here!

**Comment by F21** [comment]
A new release of `go-github` has been tagged and incorporated into this PR. This is now ready for review.

**Comment by kfcampbell** [comment]
@F21 do you mind doing me a favor when you get a moment? It would be awesome to put links to the new docs you created in the [github.erb](https://github.com/integrations/terraform-provider-github/blob/main/website/github.erb) file so they're linked and more easily accessible to users.

**Comment by F21** [comment]
Thanks for the quick review and merge @nickfloyd and @kfcampbell ! The follow-up PR to add the missing links is in #1480.

**Comment by kfcampbell** [comment]
I've merged #1480 and will release it soon, at the same time as this PR.

**Pull request merged**
