### PR TITLE
Fix: Support app auth and PAT via two provider instances

### LINKED ISSUE #1537: [FEAT]: Support app auth and PAT via two provider instances
### Describe the need

I'd like to be able to instantiate the GitHub provider twice. One instance uses app auth. The other instance uses personal access token (PAT) auth. 

The code that I'd like to write looks like this:

```tf
provider "github" { # Uses GITHUB_APP_... env vars
  app_auth {}
}

provider "github" {  # Uses GITHUB_TOKEN env var
  alias = "pat"
}
```

The first provider block errors because, although I'm not explicitly setting the `token` argument, it is set implicitly due to the existence of the env var `GITHUB_TOKEN`.

Desired behavior:
- `app_auth {}` block set => Provider uses the `GITHUB_APP_...` env vars (currently the case*), ignores `GITHUB_TOKEN` env var (new)
- `app_auth {}` block not set => Provider uses the `GITHUB_TOKEN` env var (currently the case*), ignores `GITHUB_APP_...` env vars (currently the case*)

`*` I manually confirmed these statements about current behavior. In particular, the `GITHUB_APP_...` env vars are really ignored unless the `app_auth {}` block is set.

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

```shell
│ Error: "app_auth": conflicts with token
│ 
│   with provider["registry.terraform.io/hashicorp/github"],
│   on main.tf line 1, in provider "github":
│    1: provider "github" {
│
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by MajorBreakfast**
Resolves #1537

----

### Before the change?

The following code errors if both `GITHUB_APP_...` and `GITHUB_TOKEN` env vars are set:

```tf
provider "github" { # Uses GITHUB_APP_... env vars
  app_auth {}
}
```

The error message looks like this:

```
│ Error: no decodeable PEM data found
│ 
│   with provider["registry.terraform.io/hashicorp/github"],
│   on main.tf line 1, in provider "github":
│    1: provider "github" {
```

### After the change?

- `app_auth {}` block set => Provider uses the `GITHUB_APP_...` env vars (currently the case*), ignores `GITHUB_TOKEN` env var (new)
- `app_auth {}` block not set => Provider uses the `GITHUB_TOKEN` env var (currently the case*), ignores `GITHUB_APP_...` env vars (currently the case*)

### Other information

* 

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by kfcampbell** [comment]
This PR does not take into account your proposed alias keyword in #1537. Do you view this as a transitional step? Are you going to be updating this PR?

**Comment by kfcampbell** [comment]
Alright, I've spent a little more time looking into this. I can confirm the changes are as described:
- On main
    - With app_auth set, without token set, operation succeeds
    - With app_auth set, with token set, operation fails with the ConflictsWith error
- On branch
    - With app_auth set, without token set, operation succeeds
    - With app_auth set, with token set, operation succeeds

The PR that introduced app auth, #753, mentions that the app_auth block "conflicts deliberately" with the token, but doesn't specify why. 

If this change unblocks others, I'm happy to ship it.

**Comment by MajorBreakfast** [comment]
@kfcampbell 

Thanks!

> This PR does not take into account your proposed alias keyword in #1537

[`alias`](https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations) is just Terraform's built-in way to distinguish between multiple instances of the same provider. It exists out-of-the-box on any provider.

**Comment by MajorBreakfast** [comment]
@kfcampbell any progress? Looking forward to next gh provider release with a fix :)

**Comment by MajorBreakfast** [comment]
@kfcampbell Is there an update? Looking forward to seeing this in a new version

**Review by kfcampbell — APPROVED** [review]
I'll get this merged now and released soon.

**Pull request merged**
